name: teste

on:
  push:
    branches: [ "main", "dev" ]  # Aciona o workflow nas branches 'main' e 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      - name: Determinar Branch
        id: branch
        run: echo "::set-output name=name::$(echo $GITHUB_REF | awk -F/ '{print $3}')"

      - name: Update environment.prod.ts
        run: |
          branch="${{ steps.branch.outputs.name }}"
          if [ "$branch" = "dev" ]; then
            sed -i 's|baseUrl: ".*"|baseUrl: "https://otz-homologa.com.br"|g' repo/src/environments/environment.prod.ts
          elif [ "$branch" = "main" ]; then
            sed -i 's|baseUrl: ".*"|baseUrl: "https://otz.com.br"|g' repo/src/environments/environment.prod.ts
          else
            echo "Unsupported branch"
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am "Update baseUrl in environment.prod.ts for branch ${{ steps.branch.outputs.name }}"
          git push

            
      
