name: teste

on:
  push:
    branches: [ "main", "dev" ]  # Aciona o workflow nas branches 'main' e 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        
      #- name: Determinar Branch
      #  id: branch
      #  run: echo "::set-output name=name::$(echo $GITHUB_REF | awk -F/ '{print $3}')"

      - name: Update environment.prod.ts
        run: |
          pwd
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            CONFIG="export const environment = {
            production: true,
            baseUrl: 'https://0730.otimiza.sicredi.net',
            skipAuth: false,
            };"
          else
            CONFIG="export const environment = {
            production: true,
            baseUrl: 'https://0730.otimiza-homologa.sicredi.net',
            skipAuth: false,
            };"
          fi
          echo CONFIG > src/environments/environment.prod.ts
      - name: Commit changes
        run: |
          git config --local user.email "luiz_mattos@sicredi.com.br"
          git config --local user.name "nandomattos2"
          git commit -am "Atualizar baseUrl para a branch ${{ steps.branch.outputs.name }}"
          git push

            
      
